#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=RunSample
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:20:00
#SBATCH --output=output/slurm_output_%A.out

# Load modules
module purge
module load 2023
module load Anaconda3/2023.07-2

# Initialize Conda in batch mode
source ~/.bashrc  # OR the full init path (see note below)
source activate g_retriever

export CUDA_VISIBLE_DEVICES=0

# Go to the correct working directory
cd $HOME/Multimedia-Analytics/g_retriever_m/

# QUERY="Do argument 1 and argument 2 support or counter each other? Answer in one word in the form of 'support' or 'counter'."
# seed=1

# # expla_graphs
# srun python infer_sample.py \
#     --query "$QUERY" \
#     --dataset expla_graphs \
#     --model_name graph_llm \
#     --llm_model_name 7b_chat \
#     --max_txt_len 0 \
#     --seed $seed

# QUERY="Are the white blinds to the right of a clock?"
# seed=1

# # scene_graphs
# srun python infer_sample.py \
#     --query "$QUERY" \
#     --dataset scene_graphs \
#     --model_name graph_llm \
#     --llm_model_name 7b_chat \
#     --max_txt_len 0 \
#     --seed $seed

QUERY="What is the name of justim bieber brother?"
seed=1

# webqsp
srun python infer_sample.py \
    --query "$QUERY" \
    --dataset webqsp \
    --model_name graph_llm \
    --llm_model_name 7b_chat \
    --max_txt_len 0 \
    --seed $seed